### Foundations for efficiencies

In [1]:
# Print the list created using the Non-Pythonic approach
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [2]:
# Print the list created by looping over the contents of names
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [3]:
# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [4]:
# Create a range object that goes from 0 to 5
nums = range(0,6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]


In [5]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, start=1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


In [6]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*(names_map)]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


In [7]:
#Create nums np.array()
import numpy as np
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# Print second row of nums
print('second row of nums : \n',nums[1,:],end='\n\n')
print('-------'*5, end="\n\n")

# Print all elements of nums that are greater than six
print('nums that are greater than six : \n',nums[nums > 6],end='\n\n')
print('-------'*5, end="\n\n")

# Double every element of nums
nums_dbl = nums * 2
print('Double every element of nums : \n',nums_dbl,end='\n\n')
print('-------'*5, end="\n\n")

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

second row of nums : 
 [ 6  7  8  9 10]

-----------------------------------

nums that are greater than six : 
 [ 7  8  9 10]

-----------------------------------

Double every element of nums : 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]

-----------------------------------

[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


In [8]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]
print(arrival_times)

[10, 20, 30, 40, 50]


In [9]:
# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

[ 7 17 27 37 47]


In [10]:
# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]
